# Generated by Django 2.1.3 on 2019-01-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190115_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='GSMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MID',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='MMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='suggested_retail',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='getadesarunlist',
            name='transactions',
            field=models.CharField(default='{error: error}', max_length=250),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='GSMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MID',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=models.TextField(default='{error: error}'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='suggested_retail',
            field=models.CharField(default='{error: error}', max_length=250),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='transactions',
            field=models.TextField(default='{error: error}'),
        ),
    ]
